apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: "create-angular-app-template-azure"
  title: Create Angular Template (Azure)
  description: Create a new Angular website project with Azure repository
  tags:
    - angular
    - azure
spec:
  owner: web@example.com
  type: website
  parameters:
    - title: Provide some simple information
      required:
        - component_id
        - owner
        - organization
        - project
        - repoName  
      properties:
        component_id:
          title: Name Component
          type: string
          description: Unique name of the component
          ui:field: EntityNamePicker
        name:
          title: Project name
          type: string
          description: Unique name of the component
          ui:field: EntityNamePicker
          ui:autofocus: true
        description:
          title: Description
          type: string
          description: Help others understand what this website is for.
        owner:
          title: Owner
          type: string
          description: Owner of the component
        organization:
          title: Azure DevOps Organization
          type: string
          description: The Azure DevOps organization
        project:
          title: Azure DevOps Project
          type: string
          description: The Azure DevOps project
        repoName:
          title: Repository Name For Clone 
          type: string
          description: The name of the repository to create
        authorEmail:   
          title: Author Email
          type: string
          description: Email address of the repository author
        authorName:    
          title: Author Name
          type: string
          description: Name of the repository author
  steps:
  
    - id: cloneAzureRepo
      name: Clone Azure Repo
      action: azure:repo:clone
      input:
        remoteUrl: "https://${{ parameters.organization }}@dev.azure.com/${{ parameters.organization }}/${{ parameters.project }}/_git/${{ parameters.repoName }}"
        branch: "main"
        targetPath: ./sub-directory
        
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: "https://matteomagliocchetti@dev.azure.com/matteomagliocchetti/prova-ang/_git/angular"
        targetPath: ./sub-directory
        values:
          name: ${{ parameters.name }}
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          repoName: ${{ parameters.repoName }}
          owner: ${{ parameters.owner }}
          organization: ${{ parameters.organization }}
          project: ${{ parameters.project }}
#          authorEmail: ${{ parameters.authorEmail }}  
#          authorName: ${{ parameters.authorName }}
    
    - id: pushAzureRepo
      name: Push to Remote Azure Repo
      action: azure:repo:push
      input:
        branch: "main"
        sourcePath: ./sub-directory
        gitCommitMessage: Add ${{ parameters.name }} project files       
          
#    - id: pullRequestAzureRepo
#      name: Create a Pull Request to Azure Repo
#      action: azure:repo:pr
#      input:
#        sourceBranch: "main_2"
#        targetBranch: "main"
#        repoId: ${{ parameters.repoName }}
#        title: ${{ parameters.name }}
#        project: ${{ parameters.project }}
#        supportsIterations: false
    

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: "https://${{ parameters.organization }}@dev.azure.com/${{ parameters.organization }}/${{ parameters.project }}/_git/${{ parameters.repoName }}"
        catalogInfoPath: "/catalog-info.yaml"
  output:
    links:
      - title: Repository
        url: "https://${{ parameters.organization }}@dev.azure.com/${{ parameters.organization }}/${{ parameters.project }}/_git/${{ parameters.repoName }}"
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}  
