apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-react-app-template-azure
  title: Create React App Template (Azure)
  description: Create a new CRA website project with Azure repository
  tags:
    - react
    - cra
    - azure
spec:
  owner: web@example.com
  type: website
  parameters:
    - title: Provide some simple information
      required:
        - component_id
        - owner
        - organization
        - project
        - repoName
        - authorEmail  # New parameter for author's email
        - authorName   # New parameter for author's name
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component
          ui:field: EntityNamePicker
        description:
          title: Description
          type: string
          description: Help others understand what this website is for.
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
        organization:
          title: Azure DevOps Organization
          type: string
          description: The Azure DevOps organization
        project:
          title: Azure DevOps Project
          type: string
          description: The Azure DevOps project
        repoName:
          title: Repository Name
          type: string
          description: The name of the repository to create
        authorEmail:   # New parameter
          title: Author Email
          type: string
          description: Email address of the repository author
        authorName:    # New parameter
          title: Author Name
          type: string
          description: Name of the repository author
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutTemplating:
          - .github/workflows/*
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          destination: ${{ parameters.repoName }}
          owner: ${{ parameters.owner }}
          organization: ${{ parameters.organization }}
          project: ${{ parameters.project }}
          authorEmail: ${{ parameters.authorEmail }}  # Pass author email
          authorName: ${{ parameters.authorName }}    # Pass author name
    - id: publish
      name: Publish to Azure
      action: publish:azure
      input:
        description: This is ${{ parameters.component_id }}
        repoUrl: https://dev.azure.com/${{ parameters.organization }}/${{ parameters.project }}/_git/${{ parameters.repoName }}
        allowedHosts:
          - dev.azure.com
        authorEmail: ${{ parameters.authorEmail }}  # Pass author email
        authorName: ${{ parameters.authorName }}    # Pass author name
        token: ${{ AZURE_DEVOPS_TOKEN }}
        commitMessage: "Initial commit for ${{ parameters.component_id }}"
        defaultBranch: main
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/skeleton/catalog-info.yaml"
  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
