apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: clone-and-push-template
  title: Clone and Push Template (Azure)
  description: Clone a project from one Azure DevOps repository and push it to another Azure DevOps repository
  tags:
    - azure
spec:
  owner: web@example.com
  type: website
  parameters:
    - title: Provide repository information
      properties:
        sourceRepoUrl:
          title: Source Repository URL
          type: string
          description: URL of the source Azure DevOps repository to clone from
        sourceBranch:
          title: Source Branch
          type: string
          description: Branch of the source repository to clone
        targetRepoUrl:
          title: Target Repository URL
          type: string
          description: URL of the target Azure DevOps repository to push to
        targetBranch:
          title: Target Branch
          type: string
          description: Branch of the target repository to push
  steps:
    - id: cloneAzureRepo
      name: Clone Azure Repo
      action: azure:repo:clone
      input:
        remoteUrl: "${{ parameters.sourceRepoUrl }}"
        branch: "${{ parameters.sourceBranch }}"
        targetPath: ./cloned-project
    
    - id: pushAzureRepo
      name: Push to Remote Azure Repo
      action: azure:repo:push
      input:
        branch: "${{ parameters.targetBranch }}"
        sourcePath: ./cloned-project
        remoteUrl: "${{ parameters.targetRepoUrl }}"
        gitCommitMessage: "Update project files"

  output:
    links:
      - title: Target Repository
        url: "${{ parameters.targetRepoUrl }}"
      - title: Open in Azure DevOps
        icon: azure
        url: "${{ parameters.targetRepoUrl }}"
