apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: clone-and-push-template
  title: Clone and Push Template (Azure)
  description: Clone a project from one Azure DevOps repository and push it to another Azure DevOps repository
  tags:
    - azure
spec:
  owner: web@example.com
  type: website
  parameters:
    - title: Provide repository information
      properties:
        sourceRepoUrl:
          title: Source Repository URL
          type: string
          description: URL of the source Azure DevOps repository to clone from
        sourceBranch:
          title: Source Branch
          type: string
          description: Branch of the source repository to clone
        targetRepoUrl:
          title: Target Repository URL
          type: string
          description: URL of the target Azure DevOps repository to push to
        targetBranch:
          title: Target Branch
          type: string
          description: Branch of the target repository to push
  steps:
    - id: cloneSourceRepo
      name: Clone Source Repository
      action: azure:repo:clone
      input:
        remoteUrl: "${{ parameters.sourceRepoUrl }}"
        branch: "${{ parameters.sourceBranch }}"
        targetPath: ./sub-directory-origin

    - id: cloneTargetRepo
      name: Clone Target Repository
      action: azure:repo:clone
      input:
        remoteUrl: "${{ parameters.targetRepoUrl }}"
        branch: "main"
        targetPath: ./sub-directory-des

    
        
    - id: listSubDirectoryOrigin
      name: List contents of sub-directory-origin
      action: script
      input:
        scriptType: bash
        script: |
          ls -al ./sub-directory-origin

    - id: listSubDirectoryDes
      name: List contents of sub-directory-des
      action: script
      input:
        scriptType: bash
        script: |
          ls -al ./sub-directory-des

  output:
    links:
      - title: Target Repository
        url: "${{ parameters.targetRepoUrl }}"
      - title: Open in Azure DevOps
        icon: azure
        url: "${{ parameters.targetRepoUrl }}"
