apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-react-app-azure-template
  title: Create React App Template for Azure DevOps
  description: Create a new CRA website project hosted on Azure DevOps
  tags:
    - react
    - cra
spec:
  owner: web@example.com
  type: website
  parameters:
    - title: Provide the necessary information
      required:
        - component_id
        - owner
        - repo_url
        - repo_org
        - repo_project
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component
          ui:field: EntityNamePicker
        description:
          title: Description
          type: string
          description: Help others understand what this website is for.
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
        repo_org:
          title: Azure DevOps Organization
          type: string
          description: Azure DevOps organization name
        repo_project:
          title: Azure DevOps Project
          type: string
          description: Azure DevOps project name
        repo_url:
          title: Repository Name
          type: string
          description: Name of the repository to be created
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender:
          - .azure-pipelines/*
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          destination: ${{ parameters.repo_org }}/{{ parameters.repo_project }}/{{ parameters.repo_url }}
          owner: ${{ parameters.owner }}

    - id: publish
      name: Publish
      action: publish:azure
      input:
        allowedHosts:
          - dev.azure.com
        description: This is ${{ parameters.component_id }}
        repoUrl: dev.azure.com/${{ parameters.repo_org }}/${{ parameters.repo_project }}/_git/${{ parameters.repo_url }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: Repository
        url: https://dev.azure.com/${{ parameters.repo_org }}/${{ parameters.repo_project }}/_git/${{ parameters.repo_url }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
