apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: clone-and-push-template
  title: Clone and Push Template (GitHub to Azure DevOps)
  description: Clones a GitHub repository and pushes it to Azure DevOps
spec:
  owner: web@example.com
  type: website
  parameters:
    - title: Repository Information
      required:
        - githubRepoUrl
        - azureOrg
        - azureProject
        - azureRepoName
      properties:
        githubRepoUrl:
          title: GitHub Repository URL
          type: string
          description: The URL of the GitHub repository to clone
        azureOrg:
          title: Azure DevOps Organization
          type: string
          description: The Azure DevOps organization
        azureProject:
          title: Azure DevOps Project
          type: string
          description: The Azure DevOps project
        azureRepoName:
          title: Azure DevOps Repository Name
          type: string
          description: The name of the repository to create in Azure DevOps
  steps:
    - id: cloneGitHubRepo
      name: Clone GitHub Repository
      action: git:clone
      input:
        url: ${{ parameters.githubRepoUrl }}
        targetPath: ./cloned-repo

    - id: initAzureRepo
      name: Initialize Azure Repo
      action: debug:script
      input:
        script: |
          cd ./cloned-repo
          git init
          git remote add origin "https://dev.azure.com/${{ parameters.azureOrg }}/${{ parameters.azureProject }}/_git/${{ parameters.azureRepoName }}"
          git add .
          git commit -m "Initial commit"
          git push -u origin main

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: "https://dev.azure.com/${{ parameters.azureOrg }}/${{ parameters.azureProject }}/_git/${{ parameters.azureRepoName }}?version=GBmain"
        catalogInfoPath: "/cloned-repo/catalog-info.yaml"

  output:
    links:
      - title: Azure DevOps Repository
        url: "https://dev.azure.com/${{ parameters.azureOrg }}/${{ parameters.azureProject }}/_git/${{ parameters.azureRepoName }}"
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
